const moodColors = {
  happy: "#FFD700", // Gold (Bright and joyful)
  excited: "#FF4500", // Orange-Red (Vibrant and energetic)
  calm: "#4682B4", // Steel Blue (Soothing but distinct)
  relaxed: "#32CD32", // Lime Green (Refreshing and peaceful)
  hopeful: "#FF8C00", // Dark Orange (Warm and uplifting)
  motivated: "#00CED1", // Dark Turquoise (Inspiring and bold)
  focused: "#008080", // Teal (Deep and engaging)
  neutral: "#A9A9A9", // Dark Gray (Balanced and subtle)
  sad: "#4169E1", // Royal Blue (Deep and reflective)
  lonely: "#6A5ACD", // Slate Blue (Somber but noticeable)
  anxious: "#FF6347", // Tomato (Urgent but not overwhelming)
  stressed: "#DC143C", // Crimson (Intense and warning)
  frustrated: "#B22222", // Firebrick (Strong emotional weight)
  angry: "#FF0000", // Red (Classic representation of anger)
  embarrassed: "#FF69B4", // Hot Pink (Bright and noticeable)
  bored: "#696969", // Dim Gray (Dull but visible)
  nostalgic: "#DAA520", // Goldenrod (Warm and reminiscent)
  grateful: "#008000", // Green (Associated with gratitude)
  confident: "#8B0000", // Dark Red (Powerful and bold)
  loved: "#FF1493", // Deep Pink (Romantic and affectionate)
  curious: "#8A2BE2", // Blue Violet (Mysterious and engaging)
  surprised: "#FFD700", // Gold (Bright and attention-grabbing)
  guilty: "#8B4513", // Saddle Brown (Earthy and weighty)
  ashamed: "#D2691E", // Chocolate (Muted but distinct)
  // hopeful: "#FFA500", // Orange (Warm and encouraging)
  overwhelmed: "#800080", // Purple (Heavy but striking)
  peaceful: "#00FA9A", // Medium Spring Green (Calm and fresh)
};

export default moodColors;
